# Generated by Django 4.2.5 on 2023-09-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='ocupaca',
            new_name='ocupacao',
        ),
    ]
