# Generated by Django 4.2.5 on 2023-09-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ocupaca_pessoa_ocupacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='area_saber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='area_saber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area'),
        ),
        migrations.DeleteModel(
            name='Areasaber',
        ),
    ]
