# Generated by Django 4.2.4 on 2023-09-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_semestre_primeiroperiodo_semestre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoavaliacao',
            old_name='lista_exercicio',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='tipoavaliacao',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='tipoavaliacao',
            name='prova',
        ),
        migrations.RemoveField(
            model_name='tipoavaliacao',
            name='trabalho',
        ),
    ]
